version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task_management_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_management
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_management_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=taskuser
      - DATABASE_PASSWORD=taskpassword
      - DATABASE_NAME=task_management
    depends_on:
      - mysql
    networks:
      - task_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_management_frontend
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - task_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  mysql_data:

networks:
  task_network:
    driver: bridge